### ISSUE TITLE
Create a product in the catalog

### ISSUE THREAD

**Issue by JoaoVictorLouro** [JoaoVictorLouro/agile-final-project#1]
**As a** [Store administrator]  
 **I need** [to add/create products to the store catalog]  
 **So that** [I can sell my products and earn profits]  
   
 ### Details and Assumptions
 * We need to use a relational DB
 * Use a REST API
 * NodeJS
 * Authentication will be worked on later
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [10 different products with images, names, descriptions and prices]
 When [each of the products is submitted via the product creation form]
 Then [all products are registered in the system's database]
 ```

### Tasks or Phases for this story (developer focused)

- [ ] Create nodejs server app
- [ ] Add database models and ORM utilities
- [ ] Add a rest api to save the products
