### ISSUE TITLE
Automate new change deployments to the cloud

### ISSUE THREAD

**Issue by JoaoVictorLouro** [JoaoVictorLouro/agile-final-project#10]
**As a** [Store administrator / Development team member]  
 **I need** [to deploy changes to the store code to the cloud automatically]  
 **So that** [I can be more productive and see changes reflected to my store faster, reduce time to lead]  
   
 ### Details and Assumptions
 * Use Github Actions CI
 * Use AWS CLI
 * Update docker images during builds and push them to ECR
 * Trigger EC2 update with the new image
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [a developer with the app code updated]
 When [he/she merges his changes]
 Then [the system should build a new version and deploy it to the cloud automatically]
 ```

### Tasks or Phases for this story (developer focused)

- [ ] Prepare ECR Images
- [ ] Configure github actions CI
- [ ] Automatically push to ECR on merges
- [ ] Trigger EC2 updates
