### ISSUE TITLE
Query a subset of products in the catalog

### ISSUE THREAD

**Issue by JoaoVictorLouro** [JoaoVictorLouro/agile-final-project#8]
**As a** [Store Administrator OR Customer]  
 **I need** [to be able to query the list of products in the store with specific filters]  
 **So that** [I can find products for purchasing (Customer) or Updating (Store Administrator)]  
   
 ### Details and Assumptions
 * Use existing Rest API
 * Create a new REST API for querying
 * Should be able to query by: Name (includes word, case non sensitive, ignores accents)
 * Should be able to query by: Description (includes word, case non sensitive, ignores accents)
 * Should be able to query by: Price (Larger than X amount, Less than X amount)
 * Users can use multiple Name, description or price filters at once, but not more than 1 of each type.
 * The query should be able to order products by (Name or Price), ascending or descending.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [10 products previously registered]
 When [the endpoint for querying is called, with the word "CORN"]
 Then [the server should return all products that contain the word "CORN", other products are not returned]
 ```

 ```gherkin
 Given [10 products previously registered]
 When [the endpoint for querying is called, with the word "CORN" and a price filter of "larger than 2"]
 Then [the server should return all products that contain the word "CORN" that have prices over 2 USD, other products are not returned]
 ```

 ```gherkin
 Given [10 products previously registered]
 When [the endpoint for querying is called, with a price filter of "larger than 2"]
 Then [the server should return all products that have prices over 2 USD, other products are not returned]
 ```

 ```gherkin
 Given [10 products previously registered]
 When [the endpoint for querying is called, with no filters]
 Then [the server should return all products]
 ```

### Tasks or Phases for this story (developer focused)

- [ ] Add REST API for product querying
- [ ] Implement multiple filters
- [ ] Treat accents in product names and descriptions
