### ISSUE TITLE
Host application in the cloud

### ISSUE THREAD

**Issue by JoaoVictorLouro** [JoaoVictorLouro/agile-final-project#9]
**As a** [Store administrator]  
 **I need** [the store backend is stored within a cloud provider]  
 **So that** [I can scale my systems and no worry about on premises equipment]  
   
 ### Details and Assumptions
 * We will use Docker
 * Make it deployable on AWS
 * Configuration for the service via environment variables
 * Change DNS records to point to the new instance
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [the store application in a docker format]
 When [I deploy it to AWS EC2 with the proper environment configuration]
 Then [the server should be up and running with the store system]
 ```

### Tasks or Phases for this story (developer focused)

- [ ] Dockerize application
- [ ] Publish docker images to ECR
- [ ] Spin up EC2 instance
- [ ] Deploy docker image to instance
- [ ] Change DNS records to point to the new instance
